language: python

matrix:
  include:
    - python: "3.5"
      env: BOTO_CONFIG=/tmp/nowhere
    - python: "3.6"
      env: BOTO_CONFIG=/tmp/nowhere
    - python: "3.6-dev"
      env: BOTO_CONFIG=/tmp/nowhere

install:
  - "pip install -r requirements.txt"
script: python -m unittest discover
