language: python
python:
  - "2.7"
matrix:
  include:
    - python: "3.5"
      env: BOTO_CONFIG=/tmp/nowhere

install:
  - "pip install -r requirements.txt --use-mirrors"
script: python -m unittest discover
